cmd_drivers/input/touchscreen/mediatek/tpd_init.o := /home/senya/Source/builder/aarch64-linux-android-5.3-kernel/bin/aarch64-linux-android-gcc -Wp,-MD,drivers/input/touchscreen/mediatek/.tpd_init.o.d  -nostdinc -isystem /home/senya/Source/builder/aarch64-linux-android-5.3-kernel/bin/../lib/gcc/aarch64-linux-android/5.3.1/include -I../arch/arm64/include -Iarch/arm64/include/generated  -I../include -Iinclude -I../arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I../include/uapi -Iinclude/generated/uapi -include ../include/linux/kconfig.h  -I../drivers/input/touchscreen/mediatek -Idrivers/input/touchscreen/mediatek -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -mgeneral-regs-only -fno-pic -mtune=cortex-a53 -march=armv8-a -O2 -ftree-vectorize -fno-delete-null-pointer-checks -Os -Wno-maybe-uninitialized --param=allow-store-data-races=0 -Werror=frame-larger-than=1 -Wframe-larger-than=1760 -fstack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DCC_HAVE_ASM_GOTO  -I../../drivers/misc/mediatek/include/mt-plat/ -I../drivers/misc/mediatek/include/mt-plat/  -I../../drivers/input/touchscreen/mediatek -I../drivers/input/touchscreen/mediatek    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(tpd_init)"  -D"KBUILD_MODNAME=KBUILD_STR(tpd_init)" -c -o drivers/input/touchscreen/mediatek/tpd_init.o ../drivers/input/touchscreen/mediatek/tpd_init.c

source_drivers/input/touchscreen/mediatek/tpd_init.o := ../drivers/input/touchscreen/mediatek/tpd_init.c

deps_drivers/input/touchscreen/mediatek/tpd_init.o := \

drivers/input/touchscreen/mediatek/tpd_init.o: $(deps_drivers/input/touchscreen/mediatek/tpd_init.o)

$(deps_drivers/input/touchscreen/mediatek/tpd_init.o):
