cmd_drivers/misc/mediatek/lcm/lcm_pmic.o := /home/senya/Source/builder/aarch64-linux-android-5.3-kernel/bin/aarch64-linux-android-gcc -Wp,-MD,drivers/misc/mediatek/lcm/.lcm_pmic.o.d  -nostdinc -isystem /home/senya/Source/builder/aarch64-linux-android-5.3-kernel/bin/../lib/gcc/aarch64-linux-android/5.3.1/include -I../arch/arm64/include -Iarch/arm64/include/generated  -I../include -Iinclude -I../arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I../include/uapi -Iinclude/generated/uapi -include ../include/linux/kconfig.h  -I../drivers/misc/mediatek/lcm -Idrivers/misc/mediatek/lcm -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -mgeneral-regs-only -fno-pic -mtune=cortex-a53 -march=armv8-a -O2 -ftree-vectorize -fno-delete-null-pointer-checks -Os -Wno-maybe-uninitialized --param=allow-store-data-races=0 -Werror=frame-larger-than=1 -Wframe-larger-than=1760 -fstack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DCC_HAVE_ASM_GOTO  -I../../drivers/misc/mediatek/hibcore -I../drivers/misc/mediatek/hibcore  -I../../drivers/misc/mediatek/include -I../drivers/misc/mediatek/include  -I../../drivers/misc/mediatek/include/mt-plat/mt6735/include -I../drivers/misc/mediatek/include/mt-plat/mt6735/include  -I../../drivers/misc/mediatek/include/mt-plat -I../drivers/misc/mediatek/include/mt-plat  -I../../drivers/mmc/host/mediatek/mt6735 -I../drivers/mmc/host/mediatek/mt6735  -I../../drivers/misc/mediatek/lcm/inc -I../drivers/misc/mediatek/lcm/inc  -I../../drivers/misc/mediatek/video/mt6735/dispsys -I../drivers/misc/mediatek/video/mt6735/dispsys  -I../../drivers/misc/mediatek/video/mt6735/dispsys/mt6735 -I../drivers/misc/mediatek/video/mt6735/dispsys/mt6735  -I../../drivers/misc/mediatek/video/mt6735/videox -I../drivers/misc/mediatek/video/mt6735/videox  -I../../drivers/misc/mediatek/video/include -I../drivers/misc/mediatek/video/include -DOTM1283A_CMI50_TPS65132_HD -DHX8394D_CMI50_BLJ_HD -DNT35521_BOE50_XLD_HD -DJD9365_INX50_JMG_HD -DRM68200_CPT50_BLJ_HD -DILI9881C_AUO50_XZX_HD -DRM68200_TM50_XLD_HD -DMTK_LCM_PHYSICAL_ROTATION=\"\"    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(lcm_pmic)"  -D"KBUILD_MODNAME=KBUILD_STR(lcm_pmic)" -c -o drivers/misc/mediatek/lcm/lcm_pmic.o ../drivers/misc/mediatek/lcm/lcm_pmic.c

source_drivers/misc/mediatek/lcm/lcm_pmic.o := ../drivers/misc/mediatek/lcm/lcm_pmic.c

deps_drivers/misc/mediatek/lcm/lcm_pmic.o := \

drivers/misc/mediatek/lcm/lcm_pmic.o: $(deps_drivers/misc/mediatek/lcm/lcm_pmic.o)

$(deps_drivers/misc/mediatek/lcm/lcm_pmic.o):
