cmd_drivers/misc/mediatek/fmradio/dummy.o := /home/senya/Source/builder/aarch64-linux-android-5.3-kernel/bin/aarch64-linux-android-gcc -Wp,-MD,drivers/misc/mediatek/fmradio/.dummy.o.d  -nostdinc -isystem /home/senya/Source/builder/aarch64-linux-android-5.3-kernel/bin/../lib/gcc/aarch64-linux-android/5.3.1/include -I../arch/arm64/include -Iarch/arm64/include/generated  -I../include -Iinclude -I../arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I../include/uapi -Iinclude/generated/uapi -include ../include/linux/kconfig.h  -I../drivers/misc/mediatek/fmradio -Idrivers/misc/mediatek/fmradio -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -mgeneral-regs-only -fno-pic -mtune=cortex-a53 -march=armv8-a -O2 -ftree-vectorize -fno-delete-null-pointer-checks -Os -Wno-maybe-uninitialized --param=allow-store-data-races=0 -Werror=frame-larger-than=1 -Wframe-larger-than=1760 -fstack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DCC_HAVE_ASM_GOTO  -I../../drivers/misc/mediatek/hibcore -I../drivers/misc/mediatek/hibcore  -I../../drivers/misc/mediatek/include -I../drivers/misc/mediatek/include  -I../../drivers/misc/mediatek/include/mt-plat/mt6735/include -I../drivers/misc/mediatek/include/mt-plat/mt6735/include  -I../../drivers/misc/mediatek/include/mt-plat -I../drivers/misc/mediatek/include/mt-plat  -I../../drivers/mmc/host/mediatek/mt6735 -I../drivers/mmc/host/mediatek/mt6735 -D WMT_PLAT_ALPS -D WMT_IDC_SUPPORT -D MTK_WCN_WMT_STP_EXP_SYMBOL_ABSTRACT -D MTK_WCN_REMOVE_KERNEL_MODULE  -I../drivers/misc/mediatek/fmradio/../include/mt-plat -Idrivers/misc/mediatek/fmradio/../include/mt-plat -DMT6627_FM -DMT6625_FM  -I../drivers/misc/mediatek/fmradio/inc -Idrivers/misc/mediatek/fmradio/inc  -I../drivers/misc/mediatek/fmradio/mt6627/inc -Idrivers/misc/mediatek/fmradio/mt6627/inc  -I../drivers/misc/mediatek/fmradio/../connectivity/common/conn_soc/include -Idrivers/misc/mediatek/fmradio/../connectivity/common/conn_soc/include  -I../drivers/misc/mediatek/fmradio/../connectivity/common/conn_soc/linux/include -Idrivers/misc/mediatek/fmradio/../connectivity/common/conn_soc/linux/include  -I../drivers/misc/mediatek/fmradio/../connectivity/common/common_detect -Idrivers/misc/mediatek/fmradio/../connectivity/common/common_detect    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(dummy)"  -D"KBUILD_MODNAME=KBUILD_STR(dummy)" -c -o drivers/misc/mediatek/fmradio/dummy.o ../drivers/misc/mediatek/fmradio/dummy.c

source_drivers/misc/mediatek/fmradio/dummy.o := ../drivers/misc/mediatek/fmradio/dummy.c

deps_drivers/misc/mediatek/fmradio/dummy.o := \

drivers/misc/mediatek/fmradio/dummy.o: $(deps_drivers/misc/mediatek/fmradio/dummy.o)

$(deps_drivers/misc/mediatek/fmradio/dummy.o):
